### ISSUE TITLE
doMC dependency, Windows machine more generally

### ISSUE THREAD

**Issue by daauerbach** [mccreigh/rwrfhydro#61]
Thanks for the really well-documented package. 

On a windows machine (R3.3.3), the devtools install fails on the doMC dependency (unix-alike only). For the time being I can work on a OSX machine, but any plans to switch to a Microsoft-friendly parallelization framework?

**Comment by jmccreight** [comment]
Hi Dan,

Thanks for the feedback.

It appears that you are not installing devBranch. Please try 
`devtools::install_github('mccreigh/rwrfhydro', ref='devBranch'` 
The devBranch branch should install fine on windows. If this does not solve your problem, please copy and paste the full transcript of the error here so that I have better idea of what is going on. 

In R, there is a general strategy of separating the parallelization front-ends and back-ends. DoMC is a back-end (e.g. doParallel, doSNOW, etc). We try to only implement front-ends in rwrfhydro so that the back-end is flexible. We have experienced issues with all backends on different hardware (various linux, OSX, and Windows), so we know this is critical. Here are some sites which might be helpful to browse to get familiar
http://blog.aicry.com/r-parallel-computing-in-5-minutes/
https://www.r-bloggers.com/parallel-r-loops-for-windows-and-linux/
http://blog.revolutionanalytics.com/2011/03/parallel-processing-in-r-for-windows.html
Then read anything by Steve Weston. 

I hope that helps. 

James

**Comment by daauerbach** [comment]
Worked like a charm, thanks. I have a very narrow application at the moment so I was deconstructing a few of your functions this morning via `source_url` and appreciated how clean and easy to follow they were. And, yes I'm wholly behind your strategy re: parallelization. Seems like things have improved a bunch in the last few years, and/but that's meant a fair bit of ongoing change...
